/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedBulkRouteImport } from './routes/_authenticated/bulk'
import { Route as AuthenticatedCodesRouteImport } from './routes/_authenticated/codes'
import { Route as AuthenticatedCreateRouteImport } from './routes/_authenticated/create'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDecodeRouteImport } from './routes/_authenticated/decode'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiVisitsRouteImport } from './routes/api/visits'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicRSlugRouteImport } from './routes/api/public/r.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBulkRoute = AuthenticatedBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCodesRoute = AuthenticatedCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreateRoute = AuthenticatedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecodeRoute = AuthenticatedDecodeRouteImport.update({
  id: '/decode',
  path: '/decode',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiVisitsRoute = ApiVisitsRouteImport.update({
  id: '/api/visits',
  path: '/api/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPublicRSlugRoute = ApiPublicRSlugRouteImport.update({
  id: '/api/public/r/$slug',
  path: '/api/public/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bulk': typeof AuthenticatedBulkRoute
  '/codes': typeof AuthenticatedCodesRoute
  '/create': typeof AuthenticatedCreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/decode': typeof AuthenticatedDecodeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/visits': typeof ApiVisitsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/r/$slug': typeof ApiPublicRSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/bulk': typeof AuthenticatedBulkRoute
  '/codes': typeof AuthenticatedCodesRoute
  '/create': typeof AuthenticatedCreateRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/decode': typeof AuthenticatedDecodeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/visits': typeof ApiVisitsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/r/$slug': typeof ApiPublicRSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/bulk': typeof AuthenticatedBulkRoute
  '/_authenticated/codes': typeof AuthenticatedCodesRoute
  '/_authenticated/create': typeof AuthenticatedCreateRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/decode': typeof AuthenticatedDecodeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/visits': typeof ApiVisitsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/r/$slug': typeof ApiPublicRSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/bulk'
    | '/codes'
    | '/create'
    | '/dashboard'
    | '/decode'
    | '/settings'
    | '/api/visits'
    | '/auth/callback'
    | '/api/public/r/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/bulk'
    | '/codes'
    | '/create'
    | '/dashboard'
    | '/decode'
    | '/settings'
    | '/api/visits'
    | '/auth/callback'
    | '/api/public/r/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/analytics'
    | '/_authenticated/bulk'
    | '/_authenticated/codes'
    | '/_authenticated/create'
    | '/_authenticated/dashboard'
    | '/_authenticated/decode'
    | '/_authenticated/settings'
    | '/api/visits'
    | '/auth/callback'
    | '/api/public/r/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiVisitsRoute: typeof ApiVisitsRoute
  ApiPublicRSlugRoute: typeof ApiPublicRSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bulk': {
      id: '/_authenticated/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof AuthenticatedBulkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/codes': {
      id: '/_authenticated/codes'
      path: '/codes'
      fullPath: '/codes'
      preLoaderRoute: typeof AuthenticatedCodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create': {
      id: '/_authenticated/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthenticatedCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decode': {
      id: '/_authenticated/decode'
      path: '/decode'
      fullPath: '/decode'
      preLoaderRoute: typeof AuthenticatedDecodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/visits': {
      id: '/api/visits'
      path: '/api/visits'
      fullPath: '/api/visits'
      preLoaderRoute: typeof ApiVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/public/r/$slug': {
      id: '/api/public/r/$slug'
      path: '/api/public/r/$slug'
      fullPath: '/api/public/r/$slug'
      preLoaderRoute: typeof ApiPublicRSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBulkRoute: typeof AuthenticatedBulkRoute
  AuthenticatedCodesRoute: typeof AuthenticatedCodesRoute
  AuthenticatedCreateRoute: typeof AuthenticatedCreateRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDecodeRoute: typeof AuthenticatedDecodeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBulkRoute: AuthenticatedBulkRoute,
  AuthenticatedCodesRoute: AuthenticatedCodesRoute,
  AuthenticatedCreateRoute: AuthenticatedCreateRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDecodeRoute: AuthenticatedDecodeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiVisitsRoute: ApiVisitsRoute,
  ApiPublicRSlugRoute: ApiPublicRSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
